style_title={'color': 'grey','fontSize': 30,'textAlign': 'center','font_family': 'Tahoma'}
style_text={'color': 'grey','fontSize': 15,'textAlign': 'center','font_family': 'Segoe UI'}
style_upload={'width': '300px','height': '60px','lineHeight': '60px','backgroundColor':'#EDE9EE','borderWidth': '0.2px','borderStyle': 'solid','borderColor' : '#B5B0B4','borderRadius': '5px','textAlign': 'center'}
style_load= {'width':'300px','background-color': '#EDE9EE','color': 'black','font-weight': 'bold'}
style_cats= {'color': 'grey','fontSize': 15,'textAlign': 'center','font_family': 'Segoe UI'}
style_cats2={"display":"flex", "align-items":"flex-end", 'width': '300px'}
style_btn_large = {'width':'300px','background-color': '#EDE9EE','color': 'black','font-weight': 'bold'}
style_dropdown_rand = {'width':'203px','background-color': '#F9F8F9'}
style_flex={"display":"flex", "align-items":"flex-end"}
style_input_col={'width': "153px", 'color': 'grey', 'background-color': '#F9F8F9'}
style_input_save={'width': "205px", 'color': 'grey', 'background-color': '#F9F8F9'}
style_dropdown_tbl={ 'width': "150px", 'background-color': '#F9F8F9'}
style_menu_div={'width': '250px','height': '60px','padding-left': '5%','padding-right': '5%'}
style_tbl_div={'width': '80%','height': '60vh','padding-right': '10%'}
style_current_tbl_name={'color': '#D72CA7','fontSize': 22,'textAlign': 'left','font_family': 'Segoe UI', 'padding-left': '40px'}
style_menu_and_tbl_div={'width': '100%', 'display': 'inline-flex'}
style_dbscan_btn={'background-color': '#D72CA7','color': 'white','font-weight': 'bold', 'width':'300px'}
style_dbscan_btn_div={'padding-left':'5%', 'padding-top':'300px'}
style_preview_txt={'color': 'grey','fontSize': 18,'textAlign': 'center','font_family': 'Arial'}
style_preview_tbl={'height': '100px', 'width':'300px','overflowY': 'auto', 'display':'flex'}
style_input_titles={'color': 'grey', 'textAlign': 'center'}
style_hyper_inputs={'width': '150px','background-color': '#F9F8F9'}
style_update_btn={'background-color': '#D72CA7','color': 'white','font-weight': 'bold'}
style_inputs_and_update_btns={'display':'flex',"gap":"20px", "align-items":"flex-end",'padding-left':'3%', 'padding-top':'5%'}
style_graphs_div={'display':'flex',"gap":"20px", "align-items":"flex-end",'padding-left':'3%', 'padding-top':'5%'}